---
- hosts: all
  become: true
  tasks:
  - name: install git,wget,tree using loops
    yum:
      name: "{{ item }}"
      state: present
    with_items: 
      - git
      - wget
      - tree
      